imports:
  - { resource: ./application.yaml }

services:
  Mooc.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/TypeOrmEnvironmentArranger
    arguments: ['@Mooc.ConnectionManager']
